SELECT 
    DEV.ID, DEV.EMAIL, DEV.FIRST_NAME, DEV.LAST_NAME
FROM 
    DEVELOPERS DEV
JOIN (
    SELECT SUM(CODE) AS FE_CODE_SUM
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
) FRONT ON (DEV.SKILL_CODE & FRONT.FE_CODE_SUM) != 0
ORDER BY 
    DEV.ID;